import type { Metadata } from 'next'
import { Playfair_Display, Quicksand } from 'next/font/google'
import './globals.css'
import { cn } from '../lib/utils'

const playfairDisplay = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'],
})

const quicksand = Quicksand({
  variable: '--font-quicksand',
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          playfairDisplay.variable,
          quicksand.variable,
          'antialiased',
        )}
      >
        {children}
      </body>
    </html>
  )
}
